version: '3.8'

services:

  # SERVICE 1
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - pgdb
      - redis

  # SERVICE 2
  celery:
    build: .
    command: celery -A django_project worker --loglevel=INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis

  # SERVICE 3
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres      
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  # SERVICE 4
  redis:
    image: "redis:alpine"

volumes:
  pgdata:

